version: '3.8'

services:
  backend:
    build:
      context: ./project-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.2.60:3306/MFMS_DEV
      - SPRING_DATASOURCE_USERNAME=gopi
      - SPRING_DATASOURCE_PASSWORD=gopi@1234
    networks:
      - app-network

  frontend:
    build:
      context: ./project-frontend
    ports:
      - "5173:80"
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MFMS_DEV
      MYSQL_USER: gopi
      MYSQL_PASSWORD: gopi@1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
